### ISSUE TITLE
大佬牛逼啊，我是从 weapp-vite 的依赖中找到这个项目的

### ISSUE THREAD

**Issue by sonofmagic** [F-loat/xiaoplayer#1]
之前老版本的 weapp-vite 有很多的 bug，我后面修复了很多，可以用最新版本

另外在使用过程中，遇到什么问题，欢迎提出意见和建议 https://github.com/weapp-vite/weapp-vite/issues

**Comment by F-loat** [comment]
好嘞，之前好像是有些小问题，我最近更新下看看，你做的这个工具很不错的，感觉是小程序里对 tailwind 支持度最高的了

**Comment by F-loat** [comment]
@sonofmagic 更新了已经，确实丝滑很多，不过好像需要锁一下 `esbuild` 的版本，不知道是不是我漏了什么步骤

``` json
{
  "pnpm": {
    "overrides": {
      "esbuild": "0.21.5"
    }
  }
}
```

**Comment by sonofmagic** [comment]
好的呀，用 tsup 来构建 npm，主要是因为，它和 vite 都依赖的 esbuild 来进行打包的，遇到什么问题随时问好了。
