### ISSUE TITLE
https 支持

### ISSUE THREAD

**Issue by flymin** [F-loat/xiaoplayer#2]
大佬能支持下 https 访问吗？目前域名好像不能接收协议输入，应该还是默认的 http 吧

**Comment by F-loat** [comment]
是的，我兼容下在输入框里输入协议吧

**Comment by flymin** [comment]
多谢大佬

**Comment by F-loat** [comment]
可以了应该，你在微信群里的话可以加我下微信，帮你配置下小程序的开发者，可以用体验版先试试看
